"""add users_has_feeds

Revision ID: 1310646d889e
Revises: 4ae24cbd6ddc
Create Date: 2014-04-28 11:42:15.718908

"""

# revision identifiers, used by Alembic.
revision = '1310646d889e'
down_revision = '4ae24cbd6ddc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_has_feeds',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('feeds_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feeds_id'], ['feeds.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_has_feeds')
    ### end Alembic commands ###
