"""add users_dislikes_songs

Revision ID: 140949976ecb
Revises: 1310646d889e
Create Date: 2014-05-04 23:30:37.130484

"""

# revision identifiers, used by Alembic.
revision = '140949976ecb'
down_revision = '1310646d889e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_dislikes_songs',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('songs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['songs_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_dislikes_songs')
    ### end Alembic commands ###
