"""added pub_date

Revision ID: 224b16ee675
Revises: 2d6d1ec4ccde
Create Date: 2014-04-27 17:05:48.833980

"""

# revision identifiers, used by Alembic.
revision = '224b16ee675'
down_revision = '2d6d1ec4ccde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('pub_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'pub_date')
    ### end Alembic commands ###
