"""addign uniqueness

Revision ID: 2d6d1ec4ccde
Revises: None
Create Date: 2014-04-27 16:57:56.461230

"""

# revision identifiers, used by Alembic.
revision = '2d6d1ec4ccde'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.add_column('feeds', sa.Column('title', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'feeds', ['url'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feeds')
    op.drop_column('feeds', 'title')
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('repository_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id', name=u'migrate_version_pkey')
    )
    ### end Alembic commands ###
