"""added pub_datels

Revision ID: 56b2d32003b8
Revises: 224b16ee675
Create Date: 2014-04-27 19:52:53.845155

"""

# revision identifiers, used by Alembic.
revision = '56b2d32003b8'
down_revision = '224b16ee675'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
